from reserved import *

tokens = ['PLUS',
          'MINUS',
          'TIMES',
          'DIVIDE',
          'MAT_PLUS',
          'MAT_MINUS',
          'MAT_TIMES',
          'MAT_DIVIDE',
          'ASSIGN',
          'PLUS_ASSIGN',
          'MINUS_ASSIGN',
          'TIMES_ASSIGN',
          'DIVIDE_ASSIGN',
          'GREATER',
          'LESS',
          'GREATER_EQUAL',
          'LESS_EQUAL',
          'NOT_EQUAL',
          'EQUAL',
          'OR',
          'AND',
          'NOT',
          'L_R_BRACKET',
          'R_R_BRACKET',
          'L_S_BRACKET',
          'R_S_BRACKET',
          'L_C_BRACKET',
          'R_C_BRACKET',
          'COLON',
          'TRANSPOSE',
          'COMMA',
          'SEMICOLON',
          'ID',
          'INTEGER',
          'FLOAT',
          'STRING'] + list(reserved.values())
# NOT, AND, OR?
